<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.12 setup script
 * Date: Fri, 24 Jul 2015 18:06:58 +0200
 */

$cfg['DefaultLang'] = 'it';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>